;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        god-mode-meta
        god-mode-self-insert
        kill-region
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-self-insert-command
        paredit-forward-delete
        paredit-splice-sexp
        repeat
        smex
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-kill-hybrid-sexp
        sp-kill-word
        vr/isearch-forward
        yaml-electric-backspace
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        decrease-default-font-height
        god-local-mode
        ))
