(require 'prelude-c)
(require 'prelude-coffee)
(require 'prelude-css)
(require 'prelude-emacs-lisp)
(require 'prelude-erc)
(require 'prelude-js)
(require 'prelude-lisp)
(require 'prelude-markdown)
(require 'prelude-org)
(require 'prelude-perl)
;; (require 'prelude-python)
(require 'prelude-ruby)
;; (require 'prelude-scala)
(require 'prelude-scheme)
(require 'prelude-scss)
(require 'prelude-web)
(require 'prelude-xml)
